lesson5_flask/main.py
from lesson5_flask.store_app import store_app

store_app.config.update(
    DEBUG=True,
)

if __name__=='__main__':
    store_app.run(debug=True)

lesson5_flask/views/__init__.py
from .products import products_app

lesson5_flask/views/products.py
from werkzeug.exceptions import BadRequest
from flask import Blueprint, render_template

products_app = Blueprint('products_app', __name__)

PRODUCTS = {
    1: 'BMW',
    2: 'Marsedes-benz',
    3: 'Jaguar',
    4: 'Toyota',
    5: 'Ford',
}


@products_app.route('/')
def products_page():
    return render_template('products/products_page.html', products=PRODUCTS)


@products_app.route('/<int:product_id>/', endpoint='products_detail')
def product(product_id: int):
    try:
        product_name = PRODUCTS[product_id]
    except KeyError:
        raise BadRequest(f"invalid product id #{product_id}")
    return render_template("products/products_detail.html", product_id=product_id, product_name=product_name)

lesson5_flask/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>
            {% block title %}
            Base title
            {% endblock %}
        </title>
    </head>
        <body>
        <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        <script
        src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
            <div class="container">
                    <nav class="mb-2 navbar navbar-expand-lg navbar-light bg-light">
                      <a class="navbar-brand" href="{{ url_for('index') }}">MySite</a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                          <li class="nav-item active">
                            <a class="nav-link" href="{{ url_for('products_app.products_page') }}">Products</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#">Cart</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Action
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item disabled" href="#">Personal area</a>
                              <a class="dropdown-item disabled" href="#">Support</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="#">Logout</a>
                            </div>
                          </li>
                        </ul>
                      </div>
                    </nav>
                {% block body %}
                Base page
                {% endblock %}
        </div>
        {% block after_body %}
        {% endblock %}
    </body>
</html>

lesson5_flask/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Hello
{% endblock %}

{% block body %}
    <h1>Hello {{ name }}!</h1>
{% endblock %}

lesson5_flask/templates/products/products_detail.html
{% extends 'base.html' %}

{% block title %}
Products #{{product_id}}
{% endblock %}

{% block body %}
<h1> Product <code>{{product_name}}</code> </h1>
<a href="{{ url_for('products_app.products_page') }}">Product list</a>

<hr>
{#  Admin area #}
  <div>
    <button id="delete-product" class="btn btn-danger btn-lg">Delete</button>
  </div>
{% endblock %}

{% block after_body %}
  <script>
  $(function() {
    const name = $('#product-name')
    console.log(name.text())

    $('#delete-product').click(function () {
      $.ajax({
        method: 'DELETE',
        success: function (res) {
          console.log(res)
          console.log(res.data)
        },
        error: function (err) {
          console.error(err)
        },
        complete: function () {
          window.location = "{{ url_for('products_app.products_page') }}"
        },
      })
    })
  });
  </script>

{% endblock %}

lesson5_flask/templates/products/products_page.html
{% extends 'base.html' %}

{% block title %}
Products
{% endblock %}

{% block body %}
<h1> Products list </h1>
<div class="alert alert-danger" role="alert">
    sale only today
</div>
 <div class="row">
    <div class="col col-12 col-md-8 col-lg-6 col-xl-4"> 
        <ul class="list-group">
            {% for product_id in products %}
                <li class="product-item list-group-item">
                    <a href="{{ url_for('products_app.products_detail', product_id=product_id) }}">
                        {{ products[product_id] }}
                    </a>
                </li>
            {% endfor %}    
        </ul>
    </div>

    <!-- <li></li> -->
</div>
{% endblock %}

{% block after_body %}
  <script>
    $(function () {
      const productItems = $('.product-item')
      console.log(productItems)
    });
  </script>
{% endblock %}